version: '3'

services:
  web:
    build: .
    ports:
      - "8004:8004"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8004 --reload
    restart: unless-stopped
